name: "CVM - Crate Version Manager"
description: "Automatically manage Rust crate versions with semantic versioning"
author: "BlitzForge"

branding:
  icon: "package"
  color: "orange"

inputs:
  command:
    description: "Command to run: status, apply, check-and-apply, or publish"
    required: false
    default: "check-and-apply"
  dry-run:
    description: "Run in dry-run mode (preview only)"
    required: false
    default: "false"
  create-pr:
    description: "Create a pull request with version changes"
    required: false
    default: "true"
  pr-title:
    description: "Title for the pull request"
    required: false
    default: "chore: apply version bumps"
  pr-labels:
    description: "Comma-separated labels for the PR"
    required: false
    default: "version-bump,automated"
  publish-no-tag:
    description: "Skip creating Git tags when publishing"
    required: false
    default: "false"
  publish-no-release:
    description: "Skip creating GitHub releases when publishing"
    required: false
    default: "false"
  publish-allow-dirty:
    description: "Allow publishing with uncommitted changes"
    required: false
    default: "false"

outputs:
  has-changes:
    description: "Whether there are pending version changes"
    value: ${{ steps.check.outputs.has-changes }}
  applied:
    description: "Whether changes were applied"
    value: ${{ steps.apply.outputs.applied }}
  published:
    description: "Whether crates were published"
    value: ${{ steps.publish.outputs.published }}
  version:
    description: "Version that was published (for single crate projects)"
    value: ${{ steps.publish.outputs.version }}
  crates:
    description: "JSON array of published crates with versions"
    value: ${{ steps.publish.outputs.crates }}

runs:
  using: "composite"
  steps:
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal

    - name: Cache Cargo
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: ${{ runner.os }}-cargo-cvm

    - name: Install CVM
      shell: bash
      run: |
        if ! command -v cvm &> /dev/null; then
          echo "Installing CVM..."
          cargo install cvm_cli
        else
          echo "CVM already installed"
        fi

    - name: Check for pending changes
      id: check
      shell: bash
      continue-on-error: true
      if: inputs.command != 'publish'
      run: |
        if cvm status; then
          echo "has-changes=false" >> $GITHUB_OUTPUT
        else
          echo "has-changes=true" >> $GITHUB_OUTPUT
        fi

    - name: Dry-run preview
      if: inputs.dry-run == 'true' && steps.check.outputs.has-changes == 'true' && inputs.command != 'publish'
      shell: bash
      run: cvm apply --dry-run

    - name: Apply version changes
      id: apply
      if: inputs.dry-run == 'false' && steps.check.outputs.has-changes == 'true' && inputs.command != 'publish'
      shell: bash
      run: |
        cvm apply
        echo "applied=true" >> $GITHUB_OUTPUT

    - name: Create Pull Request
      if: steps.apply.outputs.applied == 'true' && inputs.create-pr == 'true'
      uses: peter-evans/create-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      with:
        commit-message: ${{ inputs.pr-title }}
        title: ${{ inputs.pr-title }}
        body: |
          ## 🤖 Automated Version Bump

          This PR was automatically created by CVM.

          ### Changes Applied
          All pending version changes from `.cvm/changes/` have been applied.

          ### Review
          - [ ] Version numbers are correct
          - [ ] All affected crates are updated

          ---
          *Generated by [CVM Action](https://github.com/blitzforge/cvm-action)*
        labels: ${{ inputs.pr-labels }}
        branch: version-bump-${{ github.run_number }}

    - name: Publish crates
      id: publish
      if: inputs.command == 'publish'
      shell: bash
      env:
        CARGO_REGISTRY_TOKEN: ${{ env.CARGO_REGISTRY_TOKEN }}
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      run: |
        # Build publish command with flags
        PUBLISH_CMD="cvm publish"

        if [ "${{ inputs.dry-run }}" == "true" ]; then
          PUBLISH_CMD="$PUBLISH_CMD --dry-run"
        fi

        if [ "${{ inputs.publish-no-tag }}" == "true" ]; then
          PUBLISH_CMD="$PUBLISH_CMD --no-tag"
        fi

        if [ "${{ inputs.publish-no-release }}" == "true" ]; then
          PUBLISH_CMD="$PUBLISH_CMD --no-release"
        fi

        if [ "${{ inputs.publish-allow-dirty }}" == "true" ]; then
          PUBLISH_CMD="$PUBLISH_CMD --allow-dirty"
        fi

        if [ -n "$CARGO_REGISTRY_TOKEN" ]; then
          PUBLISH_CMD="$PUBLISH_CMD --token $CARGO_REGISTRY_TOKEN"
        fi

        echo "Running: $PUBLISH_CMD"

        # Run publish and capture output
        if $PUBLISH_CMD; then
          echo "published=true" >> $GITHUB_OUTPUT

          # Try to extract version info from Cargo.toml for single crate projects
          if [ -f "Cargo.toml" ] && ! grep -q "^\[workspace\]" Cargo.toml; then
            VERSION=$(grep '^version = ' Cargo.toml | head -1 | sed 's/version = "\(.*\)"/\1/')
            if [ -n "$VERSION" ]; then
              echo "version=$VERSION" >> $GITHUB_OUTPUT
            fi
          fi
        else
          echo "published=false" >> $GITHUB_OUTPUT
          exit 1
        fi
