name: Manual Publish with Preview

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Preview only (dry-run mode)'
        required: false
        type: boolean
        default: true
      create-release:
        description: 'Create GitHub releases'
        required: false
        type: boolean
        default: true
      create-tags:
        description: 'Create Git tags'
        required: false
        type: boolean
        default: true

jobs:
  preview:
    runs-on: ubuntu-latest
    if: github.event.inputs.dry-run == 'true'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Preview publish
        uses: blitzforge/cvm-action@v1
        with:
          command: 'publish'
          dry-run: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Preview Summary
        run: |
          echo "### ðŸ” Publish Preview" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "This was a **dry-run**. No changes were made." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "To actually publish, run this workflow again with:" >> $GITHUB_STEP_SUMMARY
          echo "- âœ… **Preview only**: unchecked" >> $GITHUB_STEP_SUMMARY

  publish:
    runs-on: ubuntu-latest
    if: github.event.inputs.dry-run == 'false'
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for pending changes
        id: check
        uses: blitzforge/cvm-action@v1
        with:
          command: 'status'
          create-pr: 'false'
        continue-on-error: true

      - name: Fail if pending changes exist
        if: steps.check.outputs.has-changes == 'true'
        run: |
          echo "::error::Cannot publish with pending version changes!"
          echo "Please apply pending changes first using 'cvm apply'"
          exit 1

      - name: Run tests
        run: cargo test --all-features

      - name: Publish to crates.io
        id: publish
        uses: blitzforge/cvm-action@v1
        with:
          command: 'publish'
          publish-no-release: ${{ github.event.inputs.create-release == 'false' && 'true' || 'false' }}
          publish-no-tag: ${{ github.event.inputs.create-tags == 'false' && 'true' || 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish Summary
        if: steps.publish.outputs.published == 'true'
        run: |
          echo "### ðŸš€ Publish Successful!" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ -n "${{ steps.publish.outputs.version }}" ]; then
            echo "- **Version**: v${{ steps.publish.outputs.version }}" >> $GITHUB_STEP_SUMMARY
          fi
          echo "- **Git tags created**: ${{ github.event.inputs.create-tags }}" >> $GITHUB_STEP_SUMMARY
          echo "- **GitHub releases created**: ${{ github.event.inputs.create-release }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "âœ… Published to [crates.io](https://crates.io)!" >> $GITHUB_STEP_SUMMARY
