name: Minimal Version Management & Publishing

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  version-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      # Step 1: Check for pending changes and apply them
      - name: Apply version changes
        id: apply
        uses: lucasaarch/cvm-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          pr-title: "chore: bump versions"
          pr-labels: "version-bump"

      # Step 2: Publish if no changes were pending
      # (meaning versions are already up-to-date)
      - name: Publish
        if: steps.apply.outputs.has-changes == 'false'
        uses: lucasaarch/cvm-action@v1
        with:
          command: "publish"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
